language: ruby

dist: bionic
sudo: false

rvm:
  - 2.6.5

addons:
  postgresql: "9.5"

before_install:
  - gem install bundler

before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -d travis_ci_test < db/structure.sql

script:
  - bundle exec rails test
  - bundle exec rubocop
